### ISSUE TITLE
VSI Prefix Credential Management

### ISSUE THREAD

**Issue by dwilson1988** [seerai/godal#6]
GDAL's VSI (Virtual file systems) interface looks for global credentials to access remote data such as in AWS, Azure, GCP, etc. This can be accomplished by setting environment variables or by setting global variables. Our services, primarily Boson and Tesseract need to be able to reach out to data that could be on virtually any location with multiple credentials.

With the release of GDAL 3.5, this capability is finally exposed, but this library doesn't expose those functions:
We need to implement wrappers for Set/Get/ClearCredential as defined in the C API below.
https://gdal.org/api/cpl.html#_CPPv416VSISetCredentialPKcPKcPKc

**Comment by WillGunther** [comment]
https://github.com/seerai/godal/pull/7
